module.exports = [
  {
    "Unit #": "G10.1",
    "Locus #": "001",
    "Object #": 4,
    "Body Coarse Count": 227,
    "Body Coarse Weight (g)": 2600,
    "Body Medium Count": 26,
    "Body Medium Weight (g)": 146,
    "Body Fine Count": 9,
    "Body Fine Weight (g)": 26,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 262,
    "Body Total Weight": 2772,
    "Diagnostic Coarse Count": 5,
    "Diagnostic Coarse Weight (g)": 120,
    "Diagnostic Medium Count": 5,
    "Diagnostic Medium Weight (g)": 21,
    "Diagnostic Fine Count": 1,
    "Diagnostic Fine Weight (g)": 1,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 11,
    "Diagnostic Total Weight (g)": 142,
    "Date": "7/20/2018",
    "Special Notes": "body sherds & undrawable diags dumped, body sweeties pulled, diag sweeties included in count & weight, 1 coarse platter MK"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "001",
    "Object #": 1,
    "Body Coarse Count": 750,
    "Body Coarse Weight (g)": 10920,
    "Body Medium Count": 56,
    "Body Medium Weight (g)": 504,
    "Body Fine Count": 41,
    "Body Fine Weight (g)": 223,
    "Body Marl Count": 12,
    "Body Marl Weight": 302,
    "Body Total Count": 859,
    "Body Total Weight": 11949,
    "Diagnostic Coarse Count": 16,
    "Diagnostic Coarse Weight (g)": 839,
    "Diagnostic Medium Count": 7,
    "Diagnostic Medium Weight (g)": 42,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 2,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 25,
    "Diagnostic Total Weight (g)": 883,
    "Date": "7/20/2018",
    "Special Notes": "Chipped 30 coarse, 30 med, 20 fine, all marl, body sherds & undrawable diags dumped, 2 diags early MK BJ, 2 med diags OK BJ,  1 bd3, didn't weigh sweeties"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "001",
    "Object #": 9,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 1019,
    "Body Total Weight": 12365,
    "Diagnostic Coarse Count": 21,
    "Diagnostic Coarse Weight (g)": 620,
    "Diagnostic Medium Count": 13,
    "Diagnostic Medium Weight (g)": 124,
    "Diagnostic Fine Count": 16,
    "Diagnostic Fine Weight (g)": 46,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 50,
    "Diagnostic Total Weight (g)": 790,
    "Date": "7/21/2018",
    "Special Notes": "collected sweeties for drawing, rest of diags and body sherds moved to dump, majority silt,  some MK BJ"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "002",
    "Object #": 11,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 652,
    "Body Total Weight": 10015,
    "Diagnostic Coarse Count": 19,
    "Diagnostic Coarse Weight (g)": 358,
    "Diagnostic Medium Count": 13,
    "Diagnostic Medium Weight (g)": 316,
    "Diagnostic Fine Count": 15,
    "Diagnostic Fine Weight (g)": 40,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 47,
    "Diagnostic Total Weight (g)": 714,
    "Date": "7/21/2018",
    "Special Notes": "50 chips to check future typology"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "002",
    "Object #": 13,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 724,
    "Body Total Weight": 11550,
    "Diagnostic Coarse Count": 8,
    "Diagnostic Coarse Weight (g)": 289,
    "Diagnostic Medium Count": 11,
    "Diagnostic Medium Weight (g)": 133,
    "Diagnostic Fine Count": 7,
    "Diagnostic Fine Weight (g)": 14,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 26,
    "Diagnostic Total Weight (g)": 436,
    "Date": "7/22/2018",
    "Special Notes": "mixed typology, MK vessels, amphora handles"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "001",
    "Object #": 1,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 1038,
    "Body Total Weight": 11465,
    "Diagnostic Coarse Count": 8,
    "Diagnostic Coarse Weight (g)": 79,
    "Diagnostic Medium Count": 13,
    "Diagnostic Medium Weight (g)": 41,
    "Diagnostic Fine Count": 18,
    "Diagnostic Fine Weight (g)": 32,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 39,
    "Diagnostic Total Weight (g)": 152,
    "Date": "7/22/2018",
    "Special Notes": "heavy course in body sherds but not diagnostic, diagnostic very weathered, some applique"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "002",
    "Object #": 16,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 637,
    "Body Total Weight": 9953,
    "Diagnostic Coarse Count": 14,
    "Diagnostic Coarse Weight (g)": 616,
    "Diagnostic Medium Count": 5,
    "Diagnostic Medium Weight (g)": 72,
    "Diagnostic Fine Count": 1,
    "Diagnostic Fine Weight (g)": 3,
    "Diagnostic Marl Count": 5,
    "Diagnostic Marl Weight (g)": 89,
    "Diagnostic Total Count": 25,
    "Diagnostic Total Weight (g)": 780,
    "Date": "7/22/2018",
    "Special Notes": "Marl A apparent in low quantities in both body & diag sherds"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "002",
    "Object #": 15,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 487,
    "Body Total Weight": 13695,
    "Diagnostic Coarse Count": 15,
    "Diagnostic Coarse Weight (g)": 748,
    "Diagnostic Medium Count": 9,
    "Diagnostic Medium Weight (g)": 94,
    "Diagnostic Fine Count": 5,
    "Diagnostic Fine Weight (g)": 41,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 29,
    "Diagnostic Total Weight (g)": 883,
    "Date": "7/22/2018",
    "Special Notes": "still mixed"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "002",
    "Object #": 25,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 244,
    "Body Total Weight": 4691,
    "Diagnostic Coarse Count": 11,
    "Diagnostic Coarse Weight (g)": 373,
    "Diagnostic Medium Count": 7,
    "Diagnostic Medium Weight (g)": 265,
    "Diagnostic Fine Count": 3,
    "Diagnostic Fine Weight (g)": 35,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 21,
    "Diagnostic Total Weight (g)": 673,
    "Date": "7/22/2018",
    "Special Notes": "Marl A still apparent"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "002",
    "Object #": 22,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 290,
    "Body Total Weight": 6865,
    "Diagnostic Coarse Count": 7,
    "Diagnostic Coarse Weight (g)": 592,
    "Diagnostic Medium Count": 2,
    "Diagnostic Medium Weight (g)": 21,
    "Diagnostic Fine Count": 6,
    "Diagnostic Fine Weight (g)": 34,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 15,
    "Diagnostic Total Weight (g)": 647,
    "Date": "7/22/2018",
    "Special Notes": "-"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "002",
    "Object #": 23,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 445,
    "Body Total Weight": 9160,
    "Diagnostic Coarse Count": 25,
    "Diagnostic Coarse Weight (g)": 471,
    "Diagnostic Medium Count": 15,
    "Diagnostic Medium Weight (g)": 127,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 19,
    "Diagnostic Marl Count": 2,
    "Diagnostic Marl Weight (g)": 19,
    "Diagnostic Total Count": 44,
    "Diagnostic Total Weight (g)": 636,
    "Date": "7/22/2018",
    "Special Notes": "mk BJ, platter, basin (coarse), Fine look MK"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "001",
    "Object #": 15,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 239,
    "Body Total Weight": 3610,
    "Diagnostic Coarse Count": 7,
    "Diagnostic Coarse Weight (g)": 264,
    "Diagnostic Medium Count": 6,
    "Diagnostic Medium Weight (g)": 58,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 9,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 15,
    "Diagnostic Total Weight (g)": 331,
    "Date": "7/22/2018",
    "Special Notes": "some coarse diags poorly preserved"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "002",
    "Object #": 15,
    "Body Coarse Count": 794,
    "Body Coarse Weight (g)": 13270,
    "Body Medium Count": 99,
    "Body Medium Weight (g)": 744,
    "Body Fine Count": 107,
    "Body Fine Weight (g)": 530,
    "Body Marl Count": 3,
    "Body Marl Weight": 23,
    "Body Total Count": 1003,
    "Body Total Weight": 14567,
    "Diagnostic Coarse Count": 42,
    "Diagnostic Coarse Weight (g)": 953,
    "Diagnostic Medium Count": 8,
    "Diagnostic Medium Weight (g)": 113,
    "Diagnostic Fine Count": 22,
    "Diagnostic Fine Weight (g)": 87,
    "Diagnostic Marl Count": 2,
    "Diagnostic Marl Weight (g)": 12,
    "Diagnostic Total Count": 74,
    "Diagnostic Total Weight (g)": 1165,
    "Date": "7/23/2018",
    "Special Notes": "base of bd3, m bowl"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "002",
    "Object #": 14,
    "Body Coarse Count": 265,
    "Body Coarse Weight (g)": 6750,
    "Body Medium Count": 41,
    "Body Medium Weight (g)": 248,
    "Body Fine Count": 21,
    "Body Fine Weight (g)": 125,
    "Body Marl Count": 1,
    "Body Marl Weight": 29,
    "Body Total Count": 328,
    "Body Total Weight": 7152,
    "Diagnostic Coarse Count": 21,
    "Diagnostic Coarse Weight (g)": 378,
    "Diagnostic Medium Count": 3,
    "Diagnostic Medium Weight (g)": 57,
    "Diagnostic Fine Count": 8,
    "Diagnostic Fine Weight (g)": 51,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 32,
    "Diagnostic Total Weight (g)": 486,
    "Date": "7/23/2018",
    "Special Notes": "-"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "001",
    "Object #": 1,
    "Body Coarse Count": 978,
    "Body Coarse Weight (g)": 8050,
    "Body Medium Count": 103,
    "Body Medium Weight (g)": 1070,
    "Body Fine Count": 465,
    "Body Fine Weight (g)": 1560,
    "Body Marl Count": 9,
    "Body Marl Weight": 146,
    "Body Total Count": 1555,
    "Body Total Weight": 10826,
    "Diagnostic Coarse Count": 26,
    "Diagnostic Coarse Weight (g)": 279,
    "Diagnostic Medium Count": 17,
    "Diagnostic Medium Weight (g)": 136,
    "Diagnostic Fine Count": 44,
    "Diagnostic Fine Weight (g)": 183,
    "Diagnostic Marl Count": 1,
    "Diagnostic Marl Weight (g)": 119,
    "Diagnostic Total Count": 88,
    "Diagnostic Total Weight (g)": 717,
    "Date": "23-Jul",
    "Special Notes": "small sherds compared to D09.1 & G10.1, 1 bm base"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "002",
    "Object #": 6,
    "Body Coarse Count": 1216,
    "Body Coarse Weight (g)": 7720,
    "Body Medium Count": 202,
    "Body Medium Weight (g)": 1768,
    "Body Fine Count": 95,
    "Body Fine Weight (g)": 343,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 1513,
    "Body Total Weight": 9831,
    "Diagnostic Coarse Count": 9,
    "Diagnostic Coarse Weight (g)": 67,
    "Diagnostic Medium Count": 4,
    "Diagnostic Medium Weight (g)": 79,
    "Diagnostic Fine Count": 8,
    "Diagnostic Fine Weight (g)": 23,
    "Diagnostic Marl Count": 1,
    "Diagnostic Marl Weight (g)": 10,
    "Diagnostic Total Count": 22,
    "Diagnostic Total Weight (g)": 179,
    "Date": "7/23/2018",
    "Special Notes": "7 of fine diags hem cups, includes handle diags NOT MK,"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 49,
    "Body Coarse Count": 236,
    "Body Coarse Weight (g)": 9990,
    "Body Medium Count": 15,
    "Body Medium Weight (g)": 656,
    "Body Fine Count": 3,
    "Body Fine Weight (g)": 30,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 254,
    "Body Total Weight": 10676,
    "Diagnostic Coarse Count": 9,
    "Diagnostic Coarse Weight (g)": 685,
    "Diagnostic Medium Count": 7,
    "Diagnostic Medium Weight (g)": 198,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 16,
    "Diagnostic Total Weight (g)": 883,
    "Date": "7/24/2018",
    "Special Notes": "no BJ, 1 bm rim"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 46,
    "Body Coarse Count": 197,
    "Body Coarse Weight (g)": 13158,
    "Body Medium Count": 8,
    "Body Medium Weight (g)": 197,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 205,
    "Body Total Weight": 13355,
    "Diagnostic Coarse Count": 10,
    "Diagnostic Coarse Weight (g)": 1270,
    "Diagnostic Medium Count": 5,
    "Diagnostic Medium Weight (g)": 373,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 15,
    "Diagnostic Total Weight (g)": 1643,
    "Date": "7/24/2018",
    "Special Notes": "1 bd3 base, 6 bj bases, many BJ body sherds"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 8,
    "Body Coarse Count": 277,
    "Body Coarse Weight (g)": 8398,
    "Body Medium Count": 25,
    "Body Medium Weight (g)": 283,
    "Body Fine Count": 2,
    "Body Fine Weight (g)": 8,
    "Body Marl Count": 1,
    "Body Marl Weight": 10,
    "Body Total Count": 305,
    "Body Total Weight": 8699,
    "Diagnostic Coarse Count": 5,
    "Diagnostic Coarse Weight (g)": 718,
    "Diagnostic Medium Count": 4,
    "Diagnostic Medium Weight (g)": 141,
    "Diagnostic Fine Count": 5,
    "Diagnostic Fine Weight (g)": 43,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 14,
    "Diagnostic Total Weight (g)": 902,
    "Date": "7/24/2018",
    "Special Notes": "all med diags almost coarse"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 13,
    "Body Coarse Count": 141,
    "Body Coarse Weight (g)": 3267,
    "Body Medium Count": 13,
    "Body Medium Weight (g)": 170,
    "Body Fine Count": 2,
    "Body Fine Weight (g)": 2,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 156,
    "Body Total Weight": 3439,
    "Diagnostic Coarse Count": 3,
    "Diagnostic Coarse Weight (g)": 14,
    "Diagnostic Medium Count": 2,
    "Diagnostic Medium Weight (g)": 4,
    "Diagnostic Fine Count": 1,
    "Diagnostic Fine Weight (g)": 4,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 6,
    "Diagnostic Total Weight (g)": 22,
    "Date": "7/24/2018",
    "Special Notes": "2 BJ"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "002",
    "Object #": 23,
    "Body Coarse Count": 799,
    "Body Coarse Weight (g)": 15400,
    "Body Medium Count": 98,
    "Body Medium Weight (g)": 965,
    "Body Fine Count": 9,
    "Body Fine Weight (g)": 24,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 906,
    "Body Total Weight": 16389,
    "Diagnostic Coarse Count": 39,
    "Diagnostic Coarse Weight (g)": 1025,
    "Diagnostic Medium Count": 28,
    "Diagnostic Medium Weight (g)": 630,
    "Diagnostic Fine Count": 12,
    "Diagnostic Fine Weight (g)": 110,
    "Diagnostic Marl Count": 1,
    "Diagnostic Marl Weight (g)": 1,
    "Diagnostic Total Count": 80,
    "Diagnostic Total Weight (g)": 1766,
    "Date": "24-Jul",
    "Special Notes": "NICE DIAGS, includes post-fire pot mark"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 88,
    "Body Coarse Count": 35,
    "Body Coarse Weight (g)": 941,
    "Body Medium Count": 1,
    "Body Medium Weight (g)": 6,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 36,
    "Body Total Weight": 947,
    "Diagnostic Coarse Count": 1,
    "Diagnostic Coarse Weight (g)": 65,
    "Diagnostic Medium Count": 0,
    "Diagnostic Medium Weight (g)": 0,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 1,
    "Diagnostic Total Weight (g)": 65,
    "Date": "7/25/2018",
    "Special Notes": "-"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 61,
    "Body Coarse Count": 394,
    "Body Coarse Weight (g)": 5491,
    "Body Medium Count": 14,
    "Body Medium Weight (g)": 188,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 408,
    "Body Total Weight": 5679,
    "Diagnostic Coarse Count": 5,
    "Diagnostic Coarse Weight (g)": 565,
    "Diagnostic Medium Count": 2,
    "Diagnostic Medium Weight (g)": 5,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 7,
    "Diagnostic Total Weight (g)": 570,
    "Date": "7/25/2018",
    "Special Notes": "2 BJ bases, 2BJ  1 dish"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 44,
    "Body Coarse Count": 180,
    "Body Coarse Weight (g)": 4881,
    "Body Medium Count": 8,
    "Body Medium Weight (g)": 220,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 188,
    "Body Total Weight": 5101,
    "Diagnostic Coarse Count": 8,
    "Diagnostic Coarse Weight (g)": 2770,
    "Diagnostic Medium Count": 1,
    "Diagnostic Medium Weight (g)": 65,
    "Diagnostic Fine Count": 1,
    "Diagnostic Fine Weight (g)": 2,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 10,
    "Diagnostic Total Weight (g)": 2837,
    "Date": "7/25/2018",
    "Special Notes": "7 bj bases, 1 bm base"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 56,
    "Body Coarse Count": 443,
    "Body Coarse Weight (g)": 4737,
    "Body Medium Count": 16,
    "Body Medium Weight (g)": 127,
    "Body Fine Count": 1,
    "Body Fine Weight (g)": 3,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 460,
    "Body Total Weight": 4867,
    "Diagnostic Coarse Count": 4,
    "Diagnostic Coarse Weight (g)": 915,
    "Diagnostic Medium Count": 19,
    "Diagnostic Medium Weight (g)": 655,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 9,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 25,
    "Diagnostic Total Weight (g)": 1579,
    "Date": "7/25/2018",
    "Special Notes": "-"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 39,
    "Body Coarse Count": 344,
    "Body Coarse Weight (g)": 16590,
    "Body Medium Count": 12,
    "Body Medium Weight (g)": 183,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 356,
    "Body Total Weight": 16773,
    "Diagnostic Coarse Count": 13,
    "Diagnostic Coarse Weight (g)": 1980,
    "Diagnostic Medium Count": 4,
    "Diagnostic Medium Weight (g)": 630,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 40,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 19,
    "Diagnostic Total Weight (g)": 2650,
    "Date": "7/25/2018",
    "Special Notes": "-"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 53,
    "Body Coarse Count": 363,
    "Body Coarse Weight (g)": 15821,
    "Body Medium Count": 32,
    "Body Medium Weight (g)": 955,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 1,
    "Body Marl Weight": 25,
    "Body Total Count": 396,
    "Body Total Weight": 16801,
    "Diagnostic Coarse Count": 7,
    "Diagnostic Coarse Weight (g)": 1575,
    "Diagnostic Medium Count": 12,
    "Diagnostic Medium Weight (g)": 290,
    "Diagnostic Fine Count": 1,
    "Diagnostic Fine Weight (g)": 1,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 20,
    "Diagnostic Total Weight (g)": 1866,
    "Date": "7/25/2018",
    "Special Notes": "coarse diags- 6 BJ bases"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 43,
    "Body Coarse Count": 385,
    "Body Coarse Weight (g)": 18450,
    "Body Medium Count": 14,
    "Body Medium Weight (g)": 920,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 399,
    "Body Total Weight": 19370,
    "Diagnostic Coarse Count": 11,
    "Diagnostic Coarse Weight (g)": 1990,
    "Diagnostic Medium Count": 1,
    "Diagnostic Medium Weight (g)": 4,
    "Diagnostic Fine Count": 1,
    "Diagnostic Fine Weight (g)": 2,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 13,
    "Diagnostic Total Weight (g)": 1996,
    "Date": "7/25/2018",
    "Special Notes": "ugly bj sherds"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "005",
    "Object #": 1,
    "Body Coarse Count": 806,
    "Body Coarse Weight (g)": 20460,
    "Body Medium Count": 58,
    "Body Medium Weight (g)": 825,
    "Body Fine Count": 9,
    "Body Fine Weight (g)": 80,
    "Body Marl Count": 2,
    "Body Marl Weight": 3,
    "Body Total Count": 875,
    "Body Total Weight": 21368,
    "Diagnostic Coarse Count": 36,
    "Diagnostic Coarse Weight (g)": 1380,
    "Diagnostic Medium Count": 15,
    "Diagnostic Medium Weight (g)": 455,
    "Diagnostic Fine Count": 5,
    "Diagnostic Fine Weight (g)": 9,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 56,
    "Diagnostic Total Weight (g)": 1844,
    "Date": "7/28/2018",
    "Special Notes": "-"
  },
  {
    "Unit #": "E.14.1",
    "Locus #": "004",
    "Object #": 1,
    "Body Coarse Count": 787,
    "Body Coarse Weight (g)": 8310,
    "Body Medium Count": 48,
    "Body Medium Weight (g)": 895,
    "Body Fine Count": 188,
    "Body Fine Weight (g)": 575,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 1023,
    "Body Total Weight": 9780,
    "Diagnostic Coarse Count": 28,
    "Diagnostic Coarse Weight (g)": 435,
    "Diagnostic Medium Count": 7,
    "Diagnostic Medium Weight (g)": 145,
    "Diagnostic Fine Count": 28,
    "Diagnostic Fine Weight (g)": 115,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 63,
    "Diagnostic Total Weight (g)": 695,
    "Date": "7/28/2018",
    "Special Notes": "sm sherds in OK context"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "003",
    "Object #": 1,
    "Body Coarse Count": 123,
    "Body Coarse Weight (g)": 2930,
    "Body Medium Count": 40,
    "Body Medium Weight (g)": 370,
    "Body Fine Count": 6,
    "Body Fine Weight (g)": 50,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 169,
    "Body Total Weight": 3350,
    "Diagnostic Coarse Count": 4,
    "Diagnostic Coarse Weight (g)": 995,
    "Diagnostic Medium Count": 3,
    "Diagnostic Medium Weight (g)": 8,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 3,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 9,
    "Diagnostic Total Weight (g)": 1006,
    "Date": "7/28/2018",
    "Special Notes": "-"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "003",
    "Object #": 5,
    "Body Coarse Count": 47,
    "Body Coarse Weight (g)": 360,
    "Body Medium Count": 17,
    "Body Medium Weight (g)": 150,
    "Body Fine Count": 4,
    "Body Fine Weight (g)": 6,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 68,
    "Body Total Weight": 516,
    "Diagnostic Coarse Count": 0,
    "Diagnostic Coarse Weight (g)": 0,
    "Diagnostic Medium Count": 0,
    "Diagnostic Medium Weight (g)": 0,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 0,
    "Diagnostic Total Weight (g)": 0,
    "Date": "7/28/2018",
    "Special Notes": "no diags, MK texture & treatment"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "007",
    "Object #": 1,
    "Body Coarse Count": 48,
    "Body Coarse Weight (g)": 585,
    "Body Medium Count": 5,
    "Body Medium Weight (g)": 42,
    "Body Fine Count": 2,
    "Body Fine Weight (g)": 7,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 55,
    "Body Total Weight": 634,
    "Diagnostic Coarse Count": 0,
    "Diagnostic Coarse Weight (g)": 0,
    "Diagnostic Medium Count": 3,
    "Diagnostic Medium Weight (g)": 535,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 3,
    "Diagnostic Total Weight (g)": 535,
    "Date": "7/28/2018",
    "Special Notes": "MK fabric & treatment, 2 Med diag: a large flat base, a large platter"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "009",
    "Object #": 4,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 0,
    "Body Total Weight": 0,
    "Diagnostic Coarse Count": 0,
    "Diagnostic Coarse Weight (g)": 0,
    "Diagnostic Medium Count": 1,
    "Diagnostic Medium Weight (g)": 1390,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 1,
    "Diagnostic Total Weight (g)": 1390,
    "Date": "7/29/2018",
    "Special Notes": "whole vessel- fire blackened, photographed, drawn"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "007",
    "Object #": 4,
    "Body Coarse Count": 33,
    "Body Coarse Weight (g)": 735,
    "Body Medium Count": 7,
    "Body Medium Weight (g)": 55,
    "Body Fine Count": 2,
    "Body Fine Weight (g)": 4,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 42,
    "Body Total Weight": 794,
    "Diagnostic Coarse Count": 2,
    "Diagnostic Coarse Weight (g)": 1.18,
    "Diagnostic Medium Count": 0,
    "Diagnostic Medium Weight (g)": 0,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 4,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 4,
    "Diagnostic Total Weight (g)": 5.18,
    "Date": "7/29/2018",
    "Special Notes": "slipped and nicely finished"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "003",
    "Object #": 9,
    "Body Coarse Count": 164,
    "Body Coarse Weight (g)": 2525,
    "Body Medium Count": 11,
    "Body Medium Weight (g)": 55,
    "Body Fine Count": 13,
    "Body Fine Weight (g)": 70,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 188,
    "Body Total Weight": 2650,
    "Diagnostic Coarse Count": 3,
    "Diagnostic Coarse Weight (g)": 125,
    "Diagnostic Medium Count": 6,
    "Diagnostic Medium Weight (g)": 110,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 4,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 11,
    "Diagnostic Total Weight (g)": 239,
    "Date": "7/29/2018",
    "Special Notes": "odd handmade tste"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "007",
    "Object #": 5,
    "Body Coarse Count": 421,
    "Body Coarse Weight (g)": 3405,
    "Body Medium Count": 153,
    "Body Medium Weight (g)": 980,
    "Body Fine Count": 121,
    "Body Fine Weight (g)": 415,
    "Body Marl Count": 1,
    "Body Marl Weight": 3,
    "Body Total Count": 696,
    "Body Total Weight": 4803,
    "Diagnostic Coarse Count": 18,
    "Diagnostic Coarse Weight (g)": 160,
    "Diagnostic Medium Count": 10,
    "Diagnostic Medium Weight (g)": 105,
    "Diagnostic Fine Count": 19,
    "Diagnostic Fine Weight (g)": 100,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 47,
    "Diagnostic Total Weight (g)": 365,
    "Date": "7/30/2018",
    "Special Notes": "some BM sherds"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "003",
    "Object #": 8,
    "Body Coarse Count": 28,
    "Body Coarse Weight (g)": 900,
    "Body Medium Count": 2,
    "Body Medium Weight (g)": 95,
    "Body Fine Count": 6,
    "Body Fine Weight (g)": 50,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 36,
    "Body Total Weight": 1045,
    "Diagnostic Coarse Count": 0,
    "Diagnostic Coarse Weight (g)": 0,
    "Diagnostic Medium Count": 0,
    "Diagnostic Medium Weight (g)": 0,
    "Diagnostic Fine Count": 2,
    "Diagnostic Fine Weight (g)": 1,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 2,
    "Diagnostic Total Weight (g)": 1,
    "Date": "7/30/2018",
    "Special Notes": "tossed diag fine"
  },
  {
    "Unit #": "G10.1",
    "Locus #": "009",
    "Object #": 2,
    "Body Coarse Count": 13,
    "Body Coarse Weight (g)": 225,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 13,
    "Body Total Weight": 225,
    "Diagnostic Coarse Count": 5,
    "Diagnostic Coarse Weight (g)": 525,
    "Diagnostic Medium Count": 0,
    "Diagnostic Medium Weight (g)": 0,
    "Diagnostic Fine Count": 1,
    "Diagnostic Fine Weight (g)": 5,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 6,
    "Diagnostic Total Weight (g)": 530,
    "Date": "7/30/2018",
    "Special Notes": "fine diag sm MB"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "010",
    "Object #": 6,
    "Body Coarse Count": 338,
    "Body Coarse Weight (g)": 5125,
    "Body Medium Count": 184,
    "Body Medium Weight (g)": 2140,
    "Body Fine Count": 18,
    "Body Fine Weight (g)": 170,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 540,
    "Body Total Weight": 7435,
    "Diagnostic Coarse Count": 4,
    "Diagnostic Coarse Weight (g)": 120,
    "Diagnostic Medium Count": 27,
    "Diagnostic Medium Weight (g)": 320,
    "Diagnostic Fine Count": 22,
    "Diagnostic Fine Weight (g)": 165,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 53,
    "Diagnostic Total Weight (g)": 605,
    "Date": "7/30/2018",
    "Special Notes": "large diags compared to other contexts, No BJ or BM, lots of slip in and out"
  },
  {
    "Unit #": "D09.1",
    "Locus #": "003",
    "Object #": 8,
    "Body Coarse Count": 202,
    "Body Coarse Weight (g)": 2175,
    "Body Medium Count": 75,
    "Body Medium Weight (g)": 520,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 277,
    "Body Total Weight": 2695,
    "Diagnostic Coarse Count": 0,
    "Diagnostic Coarse Weight (g)": 0,
    "Diagnostic Medium Count": 11,
    "Diagnostic Medium Weight (g)": 120,
    "Diagnostic Fine Count": 5,
    "Diagnostic Fine Weight (g)": 17,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 16,
    "Diagnostic Total Weight (g)": 137,
    "Date": "7/30/2018",
    "Special Notes": "-"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "002",
    "Object #": 26,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 0,
    "Body Total Weight": 0,
    "Diagnostic Coarse Count": 2,
    "Diagnostic Coarse Weight (g)": 505,
    "Diagnostic Medium Count": 0,
    "Diagnostic Medium Weight (g)": 0,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 2,
    "Diagnostic Total Weight (g)": 505,
    "Date": "7/30/2018",
    "Special Notes": "blat BM base- FIP"
  },
  {
    "Unit #": "E14.1",
    "Locus #": "002",
    "Object #": 9,
    "Body Coarse Count": 0,
    "Body Coarse Weight (g)": 0,
    "Body Medium Count": 0,
    "Body Medium Weight (g)": 0,
    "Body Fine Count": 0,
    "Body Fine Weight (g)": 0,
    "Body Marl Count": 0,
    "Body Marl Weight": 0,
    "Body Total Count": 0,
    "Body Total Weight": 0,
    "Diagnostic Coarse Count": 1,
    "Diagnostic Coarse Weight (g)": 765,
    "Diagnostic Medium Count": 0,
    "Diagnostic Medium Weight (g)": 0,
    "Diagnostic Fine Count": 0,
    "Diagnostic Fine Weight (g)": 0,
    "Diagnostic Marl Count": 0,
    "Diagnostic Marl Weight (g)": 0,
    "Diagnostic Total Count": 1,
    "Diagnostic Total Weight (g)": 765,
    "Date": "7/30/2018",
    "Special Notes": "painted base, well finished"
  }
]
